const tokens = {
  colors: {
    background: { value: "#f5efe7" },
    surface: { value: "#ffffff" },
    surfaceRaised: { value: "#fff8f1" },
    surfaceAlt: { value: "#f8f3ee" },
    canvas: { value: "#f6ede2" },
    textPrimary: { value: "#1f180f" },
    textSecondary: { value: "#4d4337" },
    textMuted: { value: "#7c735f" },
    muted: { value: "#5c4f44" },
    border: { value: "#d3c5b3" },
    borderSubtle: { value: "#e7ded0" },
    borderStrong: { value: "#c8b5a2" },
    primary: { value: "#a5481f" },
    primaryHover: { value: "#873418" },
    primaryActive: { value: "#63270f" },
    accentPrimary: { value: "#a5481f" },
    accentPrimaryHover: { value: "#873418" },
    accentPrimaryActive: { value: "#63270f" },
    accentSecondary: { value: "#0080c7" },
    highlight: { value: "#f1dfc8" },
    danger: { value: "#d04545" },
    info: { value: "#3867c5" },
    infoBg: { value: "#e8effb" },
    success: { value: "#2d8f58" },
    successBg: { value: "#daf5e5" },
    warning: { value: "#c08d00" },
    errorBg: { value: "#f6d7d7" },
    errorText: { value: "#a23030" },
    errorBorder: { value: "#d35858" },
    focusRing: { value: "#f2b930" },
    overlay: { value: "rgba(27, 24, 19, 0.45)" },
  },
  fonts: {
    body: { value: '"IBM Plex Sans", "Segoe UI", system-ui, sans-serif' },
    mono: { value: '"IBM Plex Mono", "SFMono-Regular", ui-monospace, monospace' },
  },
  fontSizes: {
    xs: { value: "12px" },
    sm: { value: "13px" },
    md: { value: "15px" },
    lg: { value: "17px" },
    xl: { value: "20px" },
    "2xl": { value: "24px" },
    hero: { value: "clamp(32px, 4vw, 48px)" },
  },
  spacing: {
    px: { value: "1px" },
    "0": { value: "0" },
    "1": { value: "4px" },
    "2": { value: "8px" },
    "3": { value: "12px" },
    "4": { value: "16px" },
    "5": { value: "20px" },
    "6": { value: "24px" },
    "7": { value: "28px" },
    "8": { value: "32px" },
    "9": { value: "36px" },
    "10": { value: "40px" },
    "12": { value: "48px" },
    "16": { value: "64px" },
  },
  sizes: {
    containerLg: { value: "1200px" },
    copyWidth: { value: "520px" },
    modalWidth: { value: "460px" },
    sidebarWidth: { value: "220px" },
    toolbarMin: { value: "280px" },
    searchMin: { value: "260px" },
  },
  radii: {
    sm: { value: "8px" },
    md: { value: "12px" },
    lg: { value: "16px" },
    xl: { value: "20px" },
    full: { value: "999px" },
  },
  shadows: {
    card: { value: "0 12px 30px rgba(45, 33, 21, 0.12)" },
    toolbar: { value: "0 10px 30px rgba(17, 11, 5, 0.08)" },
  },
};

export default tokens;
